services:
  finance_accumulator:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
      platforms:
        - "linux/amd64"
    image: codespice.azurecr.io/${npm_package_name}-staging:${npm_package_version}
    ports:
      - "3000:3000"
