services:
  finance_accumulator:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: ${npm_package_name}-staging:${npm_package_version}
    ports:
      - "3002:3000"
