name: Trigger auto deployment for finance-accumulator-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ staging ]
    paths:
    - '**'
    - '.github/workflows/finance-accumulator-web-AutoDeployTrigger-50a659d9-48d1-42da-aff2-13b0e77ff520.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FINANCEACCUMULATORWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINANCEACCUMULATORWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINANCEACCUMULATORWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: codespice.azurecr.io
          registryUsername: ${{ secrets.FINANCEACCUMULATORWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINANCEACCUMULATORWEB_REGISTRY_PASSWORD }}
          containerAppName: finance-accumulator-web
          resourceGroup: codespice
          imageToBuild: codespice.azurecr.io/finance-accumulator-web:${{ github.sha }}
          # _buildArgumentsKey_: |
          #   _buildArgumentsValues_


