name: Main workflow

on:
  [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      env:
        NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
        STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
        AUTH_GITHUB_ID: ${{secrets.AUTH_GITHUB_ID}}
        AUTH_GITHUB_SECRET: ${{secrets.AUTH_GITHUB_SECRET}}
        GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      with:
          build: npm run build
          start: npm start
          spec: |
            cypress/e2e/*.cy.ts

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Code linting
      run: npm run lint

    - name: Run tests and collect coverage
      run: npm run test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}